#!/usr/bin/env python
"""Generate paper/macros_audio.tex + paper tables from the NEW results schema.

Sources (all must exist for a formal build; missing file -> loud failure):
  results/e1_survival.json   (deployed baselines x attackers, calibrated metrics)
  results/e2_predictor.json  (held-out predictor validation + construction verification)
  results/e3_payload_poc.json

Every real-audio number in the manuscript is generated here so the paper cannot
drift from the code. Raw AUC and oriented AUC are BOTH emitted; operating points
carry Clopper-Pearson intervals from the calibration-set protocol.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"

ATT_ORDER = ["stft_gl", "mel80_gl", "vocos", "vocos_encodec6k", "encodec6k",
             "encodec3k", "encodec1.5k", "dac", "snac", "knnvc_self4", "knnvc_self8"]
ATT_LABEL = {
    "stft_gl": "STFT$^\\dagger$", "mel80_gl": "mel-inv", "vocos": "Vocos",
    "vocos_encodec6k": "Vc-EnC", "encodec6k": "EnC6", "encodec3k": "EnC3",
    "encodec1.5k": "EnC1.5", "dac": "DAC", "snac": "SNAC",
    "knnvc_self4": "VC$_4$", "knnvc_self8": "VC$_8$",
}
BL_LABEL = {"audioseal": "AudioSeal", "wavmark": "WavMark",
            "silentcipher": "SilentCipher"}


def f2(x): return f"{x:.2f}"
def f3(x): return f"{x:.3f}"


def load(name: str) -> dict:
    p = ROOT / "results" / name
    if not p.exists():
        raise SystemExit(f"FATAL: {p} missing — run the experiments first "
                         "(formal builds never fake numbers)")
    return json.loads(p.read_text(encoding="utf-8"))


def load_e1() -> dict:
    """Load results/e1_survival.json or merge sharded e1_survival_<baseline>.json."""
    p = ROOT / "results" / "e1_survival.json"
    if p.exists():
        return json.loads(p.read_text(encoding="utf-8"))
    shards = sorted(p for p in (ROOT / "results").glob("e1_survival_*.json")
                  if not p.stem.endswith(("_a", "_b")))
    if not shards:
        raise SystemExit("FATAL: no e1_survival results — run E1 first")
    merged = None
    for s in shards:
        d = json.loads(s.read_text(encoding="utf-8"))
        if merged is None:
            merged = d
        else:
            merged["rows"].extend(d["rows"])
            merged["attack_severity"].update(d.get("attack_severity", {}))
            if d["n_test"] != merged["n_test"]:
                raise SystemExit(f"FATAL: shard {s.name} n_test={d['n_test']} != "
                                 f"{merged['n_test']} — shards not comparable")
    return merged


def macros(e1: dict, e2: dict, e3: dict) -> list[str]:
    # v3 schema: primary response = PAIRED mel-probe transmission
    ev_m = e2["evaluation_paired_mel"]["pred_sensitivity"]
    pm_m = e2["permutation_paired_mel"]["pred_sensitivity"]
    pm_w = e2["permutation_paired_wave"]["pred_sensitivity"]
    nec = e2["necessity_test"]
    ver = e2["construction_verification"]
    null_rel = [v["ratio_rel"] for v in ver if v["kind"] == "nullspace"]
    row_rel = [v["ratio_rel"] for v in ver if v["kind"] == "rowspace"]
    by_att = e2["by_attacker_paired_mel"]

    def nec_f(probe, key):
        v = nec[probe][key]
        return "n/a" if v is None else f2(v)

    lines = [
        "% AUTO-GENERATED by scripts/make_paper_macros.py — do not edit.",
        f"\\newcommand{{\\nTest}}{{{e1['n_test']}}}",
        f"\\newcommand{{\\nCalib}}{{{e1['n_calib']}}}",
        f"\\newcommand{{\\nSpeakersTest}}{{{e1.get('n_speakers_test', '40')}}}",
        f"\\newcommand{{\\pesqTargetVal}}{{{f2(e1['pesq_target'])}}}",
        # within-attacker pooled statistic (rank-normalized per attacker)
        f"\\newcommand{{\\spearmanSens}}{{{f2(pm_m['observed_within_spearman'])}}}",
        "\\newcommand{\\spearmanSensCI}{[" +
        f2(ev_m['spearman_ci'][0]) + ", " + f2(ev_m['spearman_ci'][1]) + "]}",
        f"\\newcommand{{\\rTwoSens}}{{{f2(ev_m['isotonic']['r2'])}}}",
        f"\\newcommand{{\\permP}}{{{pm_m['p_value']:.3g}}}",
        f"\\newcommand{{\\spearmanSensWave}}{{{f2(pm_w['observed_within_spearman'])}}}",
        f"\\newcommand{{\\spearmanSNR}}"
        f"{{{f2(e2['permutation_paired_mel']['pred_snr_db']['observed_within_spearman'])}}}",
        f"\\newcommand{{\\spearmanCentroid}}"
        f"{{{f2(e2['permutation_paired_mel']['pred_spectral_centroid']['observed_within_spearman'])}}}",
        # necessity test (absolute near-null threshold; paired probes)
        f"\\newcommand{{\\necLowMel}}{{{nec_f('paired_mel', 'median_dev_low_sens')}}}",
        f"\\newcommand{{\\necRestMel}}{{{nec_f('paired_mel', 'median_dev_rest')}}}",
        f"\\newcommand{{\\necLowWave}}{{{nec_f('paired_wave', 'median_dev_low_sens')}}}",
        f"\\newcommand{{\\necMaxLowMel}}{{{nec_f('paired_mel', 'max_dev_low_sens')}}}",
        f"\\newcommand{{\\nullLeakOp}}{{{f2(float(np.median(null_rel)))}}}",
        f"\\newcommand{{\\rowLeakOp}}{{{f2(float(np.median(row_rel)))}}}",
        f"\\newcommand{{\\nullLeakEps}}{{{f2(e2.get('null_leak_eps', 0.06))}}}",
        f"\\newcommand{{\\pocBits}}{{{e3['bits']}}}",
        f"\\newcommand{{\\pocPesq}}{{{f2(e3['pesq_median'])}}}",
    ]
    # per-attacker within-Spearman (paired mel probe), for the E2 table
    for att, ev in by_att.items():
        key = att.replace("_", "").replace(".", "")
        lines.append(f"\\newcommand{{\\rhoMel{key}}}{{{f2(ev['phi_fit']['spearman'])}}}")
    return lines


def e1_table(e1: dict) -> list[str]:
    """Main table: per baseline, RAW auc / ORIENTED auc / TPR@1% per attacker."""
    rows = e1["rows"]
    atts = [a for a in ATT_ORDER
            if any(r["attacker"] == a for r in rows)]
    # average over keys
    def cell(bl: str, att: str) -> str:
        rs = [r for r in rows if r["baseline"] == bl and r["attacker"] == att]
        if not rs:
            return "--"
        raw = np.mean([r["auc_raw"] for r in rs])
        orn = np.mean([r["auc_oriented"] for r in rs])
        tpr = np.mean([r["operating_point"]["tpr"] for r in rs])
        return f"{raw:.2f}/{orn:.2f}/{tpr:.2f}"

    bls = sorted({r["baseline"] for r in rows}, key=lambda b: list(BL_LABEL).index(b))
    lines = [
        "% AUTO-GENERATED: raw AUC / oriented AUC / TPR@1%FPR (calib.-fixed threshold)",
        "\\begin{table*}[t]\\centering",
        "\\caption{Deployed watermarks under analysis--resynthesis at matched median "
        f"PESQ {e1['pesq_target']:.1f}. Cells: raw AUC\\,/\\,oriented AUC\\,/\\,TPR at "
        "the 1\\%-FPR threshold fixed on the independent calibration split "
        f"($n={e1['n_calib']}$). Raw$<$0.5 with high oriented = score sign/order "
        "inversion: operational failure with separability remaining.}",
        "\\label{tab:e1}\\footnotesize\\setlength{\\tabcolsep}{3.2pt}",
        "\\begin{tabular}{l" + "c" * (len(atts) + 1) + "}",
        "\\toprule",
        "Baseline & clean & " + " & ".join(ATT_LABEL[a] for a in atts) + " \\\\",
        "\\midrule",
    ]
    for bl in bls:
        cells = [cell(bl, "none")] + [cell(bl, a) for a in atts]
        lines.append(f"{BL_LABEL[bl]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    return lines


def main() -> None:
    e1, e2, e3 = (load_e1(), load("e2_predictor.json"),
                  load("e3_payload_poc.json"))
    (PAPER / "macros_audio.tex").write_text(
        "\n".join(macros(e1, e2, e3)) + "\n", encoding="utf-8")
    (PAPER / "tab_e1.tex").write_text(
        "\n".join(e1_table(e1)) + "\n", encoding="utf-8")
    print("wrote paper/macros_audio.tex and paper/tab_e1.tex")


if __name__ == "__main__":
    main()
